import Head from 'next/head';
import type { NextPage, GetStaticProps } from 'next';
import { Center, Heading } from '@chakra-ui/react';

import { LaptopCard } from '../components/LaptopCard';
import { IProduct } from '../interfaces/storeDataProps';
import { server } from '../utils/isDev';

interface Props {
  products: IProduct[];
}

const Home: NextPage<Props> = ({ products }) => {
  return (
    <div>
      <Head>
        <title>Laptops Prices RD</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header>
        <Center marginTop={10}>
          <Heading>Laptops Prices RD</Heading>
        </Center>
      </header>

      <main
        style={{
          padding: '4rem',
        }}
      >
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))',
            textAlign: 'center',
            gap: '20px',
          }}
        >
          {products.map((product, idx) => (
            <LaptopCard key={idx} {...product} />
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(`${server}/api/laptops`);
  const { products }: Props = await res.json();

  return {
    props: {
      products,
    },
  };
};
